export const buyHouseAndAparmentFilters = [
  {
    items: [
      { name: 'Casa', value: 'Casa' },
      { name: 'Casa 2 niveles', value: 'Casa 2 niveles' },
      { name: 'Casa 3 niveles', value: 'Casa 3 niveles' },
      { name: 'Casa 4 niveles', value: 'Casa 4 niveles' },
      { name: 'Casa en Condominio', value: 'Casa en Condominio' },
      { name: 'Apartamento', value: 'Apartamento' },
      { name: 'Apartamento en 2do Piso', value: 'Apartamento en 2do Piso' },
      { name: 'Apartamento en 3er Piso', value: 'Apartamento en 3er Piso' },
      { name: 'Apartamento en 4to Piso', value: 'Apartamento en 4to Piso' },
      { name: 'Apartametno en 5to Piso', value: 'Apartametno en 5to Piso' },
      { name: 'Penthouse', value: 'Penthouse' },
      { name: 'Apartamento de 2 niveles', value: 'Apartamento de 2 niveles' },
      { name: 'Apartamento de 3 niveles', value: 'Apartamento de 3 niveles' },
      { name: 'Loft', value: 'Loft' },
      { name: 'Casas Rural', value: 'Casas Rural' },
      { name: 'Casa de Playa', value: 'Casa de Playa' },
      { name: 'Casa Antigua pequeña', value: 'Casa Antigua pequeña' },
      { name: 'Casa Antigua Grande', value: 'Casa Antigua Grande' },
    ],
    placeholder: 'Tipo Inmueble',
    consulta: 'tipoInmueble'
  },
  {
    items: [
      { name: 'Alajuela', value: 'Alajuela' },
      { name: 'Cartago', value: 'Cartago' },
      { name: 'Guanacaste', value: 'Guanacaste' },
      { name: 'Heredia', value: 'Heredia' },
      { name: 'Limón', value: 'Limón' },
      { name: 'Puntarenas', value: 'Puntarenas' },
      { name: 'San José', value: 'San José' },
    ],
    placeholder: 'Provincia',
    consulta: 'provincia'
  },
  {
    items: [
      { name: 'Canton 1', value: 'canton1' },
      { name: 'Canton 2', value: 'canton2' },
    ],
    placeholder: 'Canton',
    consulta: 'canton'
  },
  {
    items: [
      { name: 'Distrito 1', value: 'distrito1' },
      { name: 'Distrito 2', value: 'distrito2' },
    ],
    placeholder: 'Distrito',
    consulta: 'distrito'
  },
  {
    items: [
      { name: 'Habitacional', value: 'Habitacional' },
      { name: 'Habitacional Unifamiliar', value: 'Habitacional Unifamiliar' },
      { name: 'Habitacional Bifamiliar', value: 'Habitacional Bifamiliar' },
      { name: 'Habitacional Multifamiliar', value: 'Habitacional Multifamiliar' },
      { name: 'Comercial', value: 'Comercial' },
      { name: 'Industrial', value: 'Industrial' },
      { name: 'Agrario', value: 'Agrario' },
      { name: 'Mixto Habitacional y Comercial', value: 'Mixto Habiatcional y Comercial' },
      { name: 'Mixto Habitacional e Industrial', value: 'Mixto Habiatcional e Industrial' },
      { name: 'Mixto Habitacional y Agrario', value: 'Mixto Habitacional y Agrario' },
      { name: 'Mixto Industrial y Agrario', value: 'Mixto Industrial y Agrario' },
    ],
    placeholder: 'Uso de Suelo',
    consulta: 'UsodeSuelo'
  },
  {
    items: [
      { name: 'En Condominio', value: 'En Condominio' },
      { name: 'En Residencial', value: 'En Residencial' },
      { name: 'En Urbanización', value: 'En Urbanización' },
      { name: 'En Urbanización Cerrada', value: 'En Urbanización Cerrada' },
      { name: 'En Caserío', value: 'En Caserío' },
      { name: 'En Proyecto de Interés Social', value: 'En Proyecto de Interés Social' },
      { name: 'En Zona Industrial', value: 'En Zona Industrial' },
      { name: 'En Zona Agraria', value: 'En Zona Agraria' },
      { name: 'Aislada', value: 'Aiislada' },
    ],
    placeholder: 'Ubicación Demográfica',
    consulta: 'Ubicacióndemográfica'
  },
  {
    items: [
      { name: 'Manzanero', value: 'Manzanero' },
      { name: 'Cabecero', value: 'Cabecero' },
      { name: 'Esquinero', value: 'Esquinero' },
      { name: 'Medianero', value: 'Medianero' },
      { name: 'Medianero con dos frentes', value: 'Medianero con dos frentes' },
      { name: 'Con Callejón Lateral', value: 'Con Callejón Lateral' },
      { name: 'Al fondo del Callejón', value: 'Al fondo del Callejón' },
      { name: 'En Servidumbre', value: 'En Servidumbre' },
    ],
    placeholder: 'Ubicación Catastral',
    consulta: 'Ubicacióncatastral'
  },
  {
    items: [
      { name: 'Costa en Península', value: 'Costa en Península' },
      { name: 'Costa en Cabo', value: 'Costa en Cabo' },
      { name: 'Costa en Golfo', value: 'Costa en Golfo' },
      { name: 'Costa en Bahía', value: 'Costa en Bahía' },
      { name: 'Isla', value: 'Isla' },
      { name: 'Montaña', value: 'Montaña' },
      { name: 'Valle', value: 'Valle' },
      { name: 'Llanura', value: 'Llanura' },
      { name: 'Colinda con Parque Nacional', value: 'Colinda con Parque Nacional' },
      { name: 'Colinda con Zona Volcánica', value: 'Colinda con Zona Volcánica' },
    ],
    placeholder: 'Ubicación Geográfica',
    consulta: 'Ubicacióngeográfica'
  },
  {
    items: [
      { name: '122000', value: '122000' },
      { name: '4000', value: '4000' },
      { name: '110000', value: '110000' },
    ],
    placeholder: 'Precio',
    consulta: 'precio'
  },
  {
    items: [
      { name: 'Casa Club', value: 'Casa Club' },
      { name: 'Gimnasio', value: 'Gimnasio' },
      { name: 'Piscina', value: 'Piscina' },
      { name: 'Canchas Deportivas', value: 'Canchas Deportivas' },
      { name: 'Área de Recreación Infantil', value: 'Área de Recreación Infantil' },
      { name: 'Ciclo Vía', value: 'Cíclo Vía' },
      { name: 'Parque de Mascotas', value: 'Parque de Mascotas' },
      { name: 'Senderos', value: 'Senderos' },
      { name: 'Sala de Cine', value: 'Sala de Cine' },
      { name: 'Ranchos para BBQ', value: 'Ranchos para BBQ' },
      { name: 'Sala de Internet', value: 'Sala de Internet' },
      { name: 'Guardería', value: 'Guardería' },
      { name: 'Restaurante', value: 'Restaurante' },
      { name: 'Bar', value: 'Bar' },
      { name: 'Discoteque', value: 'Discoteque' },
    ],
    placeholder: 'Amenidades',
    consulta: 'amenidades'
  },
  {
    items: [
      { name: 'Area Contruccion 1', value: 'areaContruccion1' },
      { name: 'Area Contruccion 2', value: 'areaContruccion2' },
    ],
    placeholder: 'Area Contruccion',
    consulta: 'areaContruccion'
  },
  {
    items: [
      { name: 'Area Terreno 1', value: 'areaTerreno1' },
      { name: 'Area Terreno 2', value: 'areaTerreno2' },
    ],
    placeholder: 'Area Terreno',
    consulta: 'areaTerreno'
  },
  {
    items: [
      { name: '1 Habitación', value: '1 Habitación' },
      { name: '2 Habitaciones', value: '2 Habitaciones' },
      { name: '3 Habitaciones', value: '3 Habitaciones' },
      { name: '4 Habitaciones', value: '4 Habitaciones' },
      { name: '5 Habitaciones', value: '5 Habitaciones' },
      { name: '6 Habitaciones', value: '6 Habitaciones' },
      { name: '7 Habitaciones', value: '7 Habitaciones' },
      { name: '8 Habitaciones', value: '8 Habitaciones' },
      { name: '9 Habitaciones', value: '9 Habitaciones' },
      { name: '10 Habitaciones', value: '10 Habitaciones' },
      { name: '11 Habitaciones', value: '11 Habitaciones' },
      { name: '12 Habitaciones', value: '12 Habitaciones' },
      { name: '13 Habitaciones', value: '13 Habitaciones' },
      { name: '14 Habitaciones', value: '14 Habitaciones' },
      { name: '15 Habitaciones', value: '15 Habitaciones' },
    ],
    placeholder: 'Habitaciones',
    consulta: 'Habitaciones'
  },
  {
    items: [
      { name: '1 Baño', value: '1 Baño' },
      { name: '2 Baños', value: '2 Baños' },
      { name: '3 Baños', value: '3 Baños' },
      { name: '4 Baños', value: '4 Baños' },
      { name: '5 Baños', value: '5 Baños' },
      { name: '6 Baños', value: '6 Baños' },
      { name: '7 Baños', value: '7 Baños' },
      { name: '8 Baños', value: '8 Baños' },
      { name: '9 Baños', value: '9 Baños' },
      { name: '10 Baños', value: '10 Baños' },
      { name: '11 Baños', value: '11 Baños' },
      { name: '12 Baños', value: '12 Baños' },
      { name: '13 Baños', value: '13 Baños' },
      { name: '14 Baños', value: '14 Baños' },
      { name: '15 Baños', value: '15 Baños' },
    ],
    placeholder: 'Baños',
    consulta: 'Baños'
  },
  {
    items: [
      { name: 'Si tiene Patio y Jardín', value: 'Si tiene Patio y Jardín' },
      { name: 'Solo tiene Patio', value: 'Solo tiene Patio' },
      { name: 'Solo tiene Jardín', value: 'Solo tiene Jardín' },
      { name: 'No tiene Patio ni Jardín', value: 'No tiene Patio ni Jardín' },
    ],
    placeholder: 'Patio o Jardín',
    consulta: 'patioOJardín'
  },
  {
    items: [
      { name: '1 Cochera Techada', value: '1 Cochera techada' },
      { name: '2 Cocheras Techadas', value: '2 Cocheras Techadas' },
      { name: '3 Cocheras Techadas', value: '3 Cocheras Techadas' },
      { name: '4 Cocheras Techadas', value: '4 Cocheras Techadas' },
      { name: '5 Cocheras Techadas', value: '5 Cocheras Techadas' },
      { name: '6 Cocheras Techadas', value: '6 Cocheras Techadas' },
      { name: '7 Cocheras Techadas', value: '7 Cocheras Techadas' },
      { name: '8 Cocheras Techadas', value: '8 Cocheras Techadas' },
      { name: '9 Cocheras Techadas', value: '9 Cocheras Techadas' },
      { name: '10 Cocheras Techadas', value: '10 Cocheras Techadas' },
      { name: 'Más de 11 Cocheras Techadas', value: 'Más de 11 Cocheras Techadas' },
    ],
    placeholder: 'Cocheras Techadas',
    consulta: 'Cocheras'
  },
  {
    items: [
      { name: '1 Estacionamiento Destechado', value: '1 Estacionamiento Destechado' },
      { name: '2 Estacionamientos Destechados', value: '2 Estacionamientos Destechados' },
      { name: '3 Estacionamientos Destechados', value: '3 Estacionamientos Destechados' },
      { name: '4 Estacionamientos Destechados', value: '4 Estacionamientos Destechados' },
      { name: '5 Estacionamientos Destechados', value: '5 Estacionamientos Destechados' },
      { name: '6 Estacionamientos Destechados', value: '6 Estacionamientos Destechados' },
      { name: '7 Estacionamientos Destechados', value: '7 Estacionamientos Destechados' },
      { name: '8 Estacionamientos Destechados', value: '8 Estacionamientos Destechados' },
      { name: '9 Estacionamientos Destechados', value: '9 Estacionamientos Destechados' },
      { name: '10 Estacionamientos Destechados', value: '10 Estacionamientos Destechados' },
      { name: 'Más de 11 Estacionamientos Destechados', value: 'Más de 11 Estacionamientos Destechados' },
    ],
    placeholder: 'Estacionamientos Destechados',
    consulta: 'Estacionamientos'
  },
  {
    items: [
      { name: 'Acondicionado a la Ley 7600', value: 'Acondicionado a la ley 7600' },
      { name: 'No Acondicionado a la Ley 7600', value: 'No Acondicionado a la ley 7600' },
      { name: 'Semi acondicionado a la Ley 7600', value: 'Semi acondicionado a la ley 7600' },
    ],
    placeholder: 'Ley 7600',
    consulta: 'ley7600'
  },
  {
    items: [
      { name: 'Terraza', value: 'Terraza' },
      { name: 'Balcón', value: 'Balcón' },
      { name: 'Adosado', value: 'Adosado' },
      { name: 'Alarma', value: 'Alarma' },
      { name: 'Armarios Empotrados', value: 'Armarios Empotrados' },
      { name: 'Baño Auxiliar', value: 'Baños Auxiliar' },
      { name: 'Cuarto de Pánico', value: 'Cuarto de Pánico' },
      { name: 'Baño en Habitación Principal', value: 'Baño en Habitación Principal' },
      { name: 'Barra Estilo Americano', value: 'Barra Estilo Americano' },
      { name: 'Biblioteca / Estudio', value: 'Biblioteca / Estudio' },
      { name: 'Habitación de Servicio', value: 'Habitación de Servicio' },
      { name: 'Habitación del Conductor', value: 'Habitación del Conductor' },
      { name: 'Cuarto para Visitas', value: 'Cuarto para Visitas' },
      { name: 'Cuarto de Pilas', value: 'Cuarto de Pilas' },
      { name: 'Sótano', value: 'Sótano' },
      { name: 'Desván', value: 'Desván' },
      { name: 'xBifamiliar', value: 'Bifamiliar' },
      { name: 'Bodega', value: 'Bodega' },
      { name: 'Despenza', value: 'Despenza' },     
      { name: 'Calentador', value: 'Calentador' },
      { name: 'Chimenea', value: 'Chimenea' },
      { name: 'Citófono / Intercomunicador', value: 'Citófono / Intercomunicador' },
      { name: 'Closets', value: 'Closets' },
      { name: 'Closets full altura', value: 'Closets full altura' },
      { name: 'Cocina Equipada', value: 'Cocina Equipada' },
      { name: 'Cocina Tipo Americano', value: 'Cocina Tipo Americano' },
      { name: 'Cocina empotrada', value: 'Cocina Empotrada' },
      { name: 'Comedor Auxiliar', value: 'Comedor Auxiliar' },
      { name: 'Doble Ventana', value: 'Doble Ventana' },
      { name: 'Traga Luz', value: 'Traga Luz' },
      { name: 'Gas Domiciliario', value: 'Gas Domiciliario' },    
      { name: 'Hall de Alcobas', value: 'Hall de Alcobas' },
      { name: 'Jacuzzi', value: 'Jacuzzi' },
      { name: 'Sauna', value: 'Sauna' },
      { name: 'Gimnasio Interno', value: 'Gimnasio Interno' },
      { name: 'Sala de Internet', value: 'Sala de Internet' },
      { name: 'Turco', value: 'Turco' },
      { name: 'Vista Panorámica', value: 'Vista Panorámica' },
      { name: 'Cuarto para Mascota', value: 'Cuarto para Mascota' },
    ],
    placeholder: 'Caracteristicas Internas',
    consulta: 'Caracteristicas Internas'
  },
  {
    items: [
      { name: 'Transporte Público Cercano', value: 'Transporte Público Cercano' },
      { name: 'Portería / Recepción', value: 'Portería / Recepción' },
      { name: 'Servicio de Vigilancia', value: 'Servicio de Vigilancia' },
      { name: 'Transporte Interno Privado', value: 'Transporte Interno Privado' },
      { name: 'Acceso Adoquinado', value: 'Accesos Adoquinado' },
      { name: 'Acceso Pavimentado', value: 'Acceso Pavimentado' },
      { name: 'Zonas Verdes', value: 'Zonas Verdes' },
      { name: 'Senderos', value: 'Senderos' },
      { name: 'Calles de Tosca', value: 'Calles de Tosca' },
      { name: 'Árboles Frutales', value: 'Árboles Frutales' },
      { name: 'Sistema de Riego', value: 'Sistema de Riego' },
      { name: 'Ascensor', value: 'Ascensor' },
      { name: 'Bungalow / Pareado', value: 'Bungalow / Pareado' },
      { name: 'Establo', value: 'Establo' },
      { name: 'Pecebre', value: 'Pecebre' },
      { name: 'Galpón', value: 'Galpón' },
      { name: 'Garita de Entrada', value: 'Garita de Entrada' },
      { name: 'Invernadero', value: 'Invernadero' },
      { name: 'Kiosko', value: 'Kiosko' },
      { name: 'Zona Campestre', value: 'Zona Campestre' },
      { name: 'Zona de Camping', value: 'Zona de Camping' },
      { name: 'Río / Quebrada Cercana', value: 'Río / Quebrada Cercana' },
      { name: 'Pozo de Agua Natural', value: 'Pozo de Agua Natural' },
      { name: 'Lago', value: 'Lago' },
      { name: 'Laguna', value: 'Laguna' },
      { name: 'Montaña', value: 'Montaña' },
      { name: 'Playa', value: 'Playa' },
      { name: 'Oficina de Negocios', value: 'Oficina de Negocios' },
      { name: 'Parqueo de Visitantes', value: 'Parqueo de Visitantes' },
      { name: 'Parque Infatil', value: 'Parque Infantil' },
      { name: 'Planta Eléctrica', value: 'Plánta Eléctrica' },
    ],
    placeholder: 'Características Externas',
    consulta: 'Características Externas'
  },
  {
    items: [
      { name: 'Código', value: 'Código' },
    ],
    placeholder: 'Buscar por Código Identificador',
    consulta: 'Buscarporcódigo'
  },
]
